<!doctype html>
<html lang="<?= $this->language ?>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= $this->title ?></title>
    <style>
        body {
            font-family: sans-serif;
            margin: 0;
        }

        main {
            margin: .5rem;
        }

        .hidden {
            display: none !important;
        }
    </style>
    <script>
        function toggle(trigger) {
            trigger.classList.toggle('active');
            toggleClass(trigger.dataset.toggleId, trigger.dataset.toggle);
        }

        function toggleClass(id, cssClass) {
            document.getElementById(id).classList.toggle(cssClass);
        }
    </script>
</head>
<body>
<header>
    <?= $this->header ?>
</header>
<main>
    <?= $this->main ?>
</main>
</body>
</html>