<!doctype html>
<html lang="<?= $this->language ?>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= $this->title ?></title>
    <script>
        function toggle(trigger) {
            trigger.classList.toggle('active');
            toggleClass(trigger.dataset.toggleId, trigger.dataset.toggle);
        }

        function toggleClass(id, cssClass) {
            document.getElementById(id).classList.toggle(cssClass);
        }
    </script>
    <?php foreach ($this->entrypoints['entrypoints']['admin']['css'] ?? [] as $file): ?>
        <link rel="stylesheet" href="<?= $file ?>"
    <?php endforeach; ?>
</head>
<body>
<header>
    <?= $this->header ?>
</header>
<main>
    <?= $this->main ?>
</main>

<?php foreach ($this->entrypoints['entrypoints']['admin']['js'] ?? [] as $file): ?>
    <script defer src="<?= $file ?>"></script>
<?php endforeach; ?>
</body>
</html>