---
# Add 'repo' label to any root file changes
repo:
  - "*"

# Add 'domain/core' label to any change within the 'core' package
domain/core:
  - "src/Core/*"
  - "src/Core/**/*"

domain/app:
  - "src/App/*"
  - "src/App/**/*"

domain/config:
  - "config/*"
  - "config/**/*"
  
domain/github:
  - ".github/*"
  - ".github/**/*"

domain/docker:
  - "docker/*"
  - "docker/**/*"
  - "docker-compose.*"

domain/docs:
  - "docs/*"
  - "docs/**/*"

public:
  - "public/*"
  - "public/**/*"

# Add 'php' label to any change to src php files within the source or test dir
php:
  - "src/**/*.php"
  - "test/**/*.php"

# Add filetype labels to any change
ts:
  - "src/**/*.ts"
js:
  - "src/**/*.js"
scss:
  - "src/**/*.scss"
css:
  - "src/**/*.css"
yml:
  - "*.yml"
  - "**/*.yml"
xml:
  - "*.xml"
  - "**/*.xml"
json:
  - "*.json"
  - "**/*.json"
