<?php
/** @var Pars\Core\View\Layout\Layout $this */

?>
<!doctype html>
<html lang="<?= $this->language ?>">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title><?= $this->title ?></title>
    <?= Pars\Core\View\Entrypoints::dumpCss(); ?>
</head>
<body>
<?php if (!empty($this->header)): ?>
    <header>
        <?= $this->header ?>
    </header>
<?php endif; ?>
<?php if (!empty($this->main)): ?>
    <main>
        <?= $this->main; ?>
    </main>
<?php endif; ?>
<?php if (!empty($this->footer)): ?>
    <footer>
        <?= $this->footer ?>
    </footer>
<?php endif; ?>
<?= Pars\Core\View\Entrypoints::dumpJs(); ?>
</body>
</html>