<ul class="navigation<?= $this->model->hidden ? ' hidden' : '' ?>" id="<?= $this->model->getId() ?>">
    <?php foreach ($this->model as $item): ?>
        <li class="navigation__item<?= $item->isList() ? ' toggle' : '' ?>">
            <a href="<?= $item->link ?>" class="navigation__link<?= $item->isActive() ? ' active' : '' ?>"><?= $item->value ?></a>
            <?php if ($item->isList()): ?>
                <span class="navigation__toggle"
                      onclick="toggle(this)" data-toggle="hidden" data-toggle-id="<?= $item->getId() ?>"
                ></span>
            <?php endif; ?>
        </li>
    <?php endforeach; ?>
</ul>
<div class="subnavigation">
    <?php $model = $this->model; ?>
    <?php foreach ($model as $item): ?>
        <?php if ($item->isList()): ?>
            <?php $this->model = $item; ?>
            <?php $this->model->hidden = true; ?>
            <?php include __FILE__; ?>
        <?php endif; ?>
    <?php endforeach; ?>
</div>
<style>
    .navigation {
        display: flex;
        position: relative;
        flex-wrap: wrap;
        padding: .5rem;
        margin: 0;
        background: #ddd;
        list-style: none;
    }

    @media screen and (min-width: 320px) {
        .navigation {
            flex-direction: row;
        }
    }

    .navigation__item {
        padding: .25rem .5rem;
    }

    .navigation__item.toggle {
        padding-right: 2rem;
    }

    .navigation__link {
        position: relative;
        color: #555;
        text-decoration: none;
    }

    .navigation__link.active,
    .navigation__link:hover,
    .navigation__link:focus {
        color: #000;
    }

    .navigation__link:after {
        content: '';
        position: absolute;
        left: 0;
        bottom: 1px;
        width: 100%;
        border-bottom: 2px solid black;
        opacity: 0;
        transition: .2s ease-in-out;
    }

    .navigation__link.active:after,
    .navigation__link:hover:after {
        opacity: 1;
        bottom: -1px;
    }
    .navigation__toggle {
        position: relative;
    }

    .navigation__toggle:after {
        content: '';
        position: absolute;
        width: 10px;
        height: 10px;
        left: 10px;
        border-bottom: 1px solid black;
        border-right: 1px solid black;
        transform: rotate(45deg);
        cursor: pointer;
        transition: .2s ease-in-out;
    }

    .navigation__toggle.active:after {
        transform: rotate(-135deg);
        top: 5px;
    }
</style>
