version: '3'

services:
  php-swoole:
    build:
      context: ./docker/php-swoole
    volumes:
      - .:/var/www
      - ./docker/php-swoole/php.ini:/usr/local/etc/php/php.ini
    links:
      - mariadb
    depends_on:
      - mariadb
    ports:
      - "8080:8080"
  mariadb:
    build:
      context: ./docker/mariadb
    environment:
      - MYSQL_DATABASE=pars
      - MYSQL_USER=pars
      - MYSQL_PASSWORD=pars
      - MYSQL_ROOT_PASSWORD=pars
    volumes:
      - ./data/mariadb:/var/lib/mysql
