version: '3'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm-dev
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CONFIG: >-
        client_host=host.docker.internal
        idekey=PHPSTORM
      PHP_IDE_CONFIG: serverName=localhost:8080
    expose:
      - 9000
      - 9003
  yarn:
    image: node:16.14.2
    command: [ "sh", "/development.sh" ]
    working_dir: /app
    volumes:
      - ./docker/yarn/development.sh:/development.sh
      - .:/app
  mariadb:
    ports:
      - "3306:3306"