version: '3'

services:
  php-swoole:
    build:
      context: ./docker/php-swoole
    volumes:
      - ./docker/php-swoole-dev/boot.sh:/usr/local/boot/boot.sh
    environment:
      - DEV_DOMAIN=localhost
  yarn:
    image: node:16.14.2
    command: [ "sh", "/development.sh" ]
    working_dir: /app
    volumes:
      - ./docker/yarn/development.sh:/development.sh
      - .:/app
  mariadb:
    ports:
      - "3306:3306"