<?php
namespace Pars\Core\View\Editor;
/* @var \Pars\Core\View\Editor\Editor $this */
?>
<div class="editor">
    <div class="content">

    </div>
    <div class="tools">
        <div class="tabbed">
            <nav>
            </nav>
            <label class="tab" for="tab1">Berlin</label>

            <input class="state" checked id="tab1" type="radio" name="tabs"/>

            <div class="content"> … tab 1</div>
            <label class="tab" for="tab2">London</label>

            <input class="state" id="tab2" type="radio" name="tabs"/>

            <div class="content"> … tab 2</div>
            <label class="tab" for="tab3">Paris</label>

            <input class="state" id="tab3" type="radio" name="tabs"/>

            <div class="content"> … tab 3</div>


        </div>
    </div>
</div>
