<?php
/**
 * @var $this \Pars\Core\View\Navigation\NavigationItem
 */
?>
<li class="navigation__item <?= $this->getModel()->isActive() ? 'active' : '' ?>"
    onmouseenter="this.classList.add('hover')"
    onmouseleave="this.classList.remove('hover')"
>
    <a href="<?= $this->getModel()->getLink() ?>" class="navigation__link <?= $this->getModel()->isActive() ? ' active' : '' ?>">
        <?= $this->getModel()->getValue() ?>
    </a>
    <?= $this->getContent() ?>
</li>
