<?php
/* @var Pars\Core\View\Tree\TreeItem $this */

?>
<li class="tree__item<?= $this->hasItems() ? ' items' : '' ?><?= $this->getModel()->isOpen() ? ' open' : '' ?>">
    <p class="tree__value<?= $this->getModel()->isActive() ? ' active' : '' ?>" <?= $this->attr() ?>>
        <svg class="icon">
            <use href="/icons.svg#<?= $this->getModel()->getIcon() ?>"/>
        </svg>
        <?= $this->getModel()->getValue() ?>
    </p>
    <?= $this->getContent() ?>
</li>
