<?php
/* @var Pars\Core\View\Tree\TreeItem $this */

?>
<li class="tree__item<?= $this->hasItems() ? ' items' : '' ?><?= $this->getModel()->isOpen() ? ' open' : '' ?>">
    <p class="tree__value<?= $this->getModel()->isActive() ? ' active' : '' ?>" <?= $this->attr() ?>>
        <?php if ($this->hasItems()): ?>
            <svg class="icon">
                <use href="/icons.svg#folder"/>
            </svg>
        <?php else: ?>
            <svg class="icon">
                <use href="/icons.svg#file"/>
            </svg>
        <?php endif; ?>
        <?= $this->getModel()->getValue() ?>
    </p>
    <?= $this->getContent() ?>
</li>
