name: Static Analysis

on:
  pull_request:
    types: [ labeled ]

jobs:
  phpstan:
    if: ${{ github.event.label.name == 'php' }}
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: php-actions/composer@v6
        with:
          php_version: "8.1"
          php_extensions: intl pdo
          version: 2
      - run: composer phpstan